#############################################################################
# Makefile for building: QmlGame
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  QmlGame.pro
# Template: app
# Command: /home/ingmar/Programs/Qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QmlGame.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I../../Programs/Qt/5.4/gcc_64/include -I../../Programs/Qt/5.4/gcc_64/include/QtQuick -I../../Programs/Qt/5.4/gcc_64/include/QtWidgets -I../../Programs/Qt/5.4/gcc_64/include/QtGui -I../../Programs/Qt/5.4/gcc_64/include/QtQml -I../../Programs/Qt/5.4/gcc_64/include/QtNetwork -I../../Programs/Qt/5.4/gcc_64/include/QtCore -I. -I../../Programs/Qt/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ingmar/Programs/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QmlGame1.0.0
DISTDIR = /home/ingmar/Development/qmlgame/.tmp/QmlGame1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ingmar/Programs/Qt/5.4/gcc_64 -Wl,-rpath,/home/ingmar/Programs/Qt/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/ingmar/Programs/Qt/5.4/gcc_64/lib -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = ../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qml_debug.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/resources.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/moc.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/uic.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		QmlGame.pro  main.cpp
QMAKE_TARGET  = QmlGame
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QmlGame


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QmlGame.pro ../../Programs/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qml_debug.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/resources.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/moc.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/uic.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../Programs/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		QmlGame.pro \
		qml.qrc \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Quick.prl \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Gui.prl \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Core.prl \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Qml.prl \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Network.prl \
		/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Widgets.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QmlGame.pro
../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/unix.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/linux.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/qconfig.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/default_post.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/qml_debug.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/declarative_debug.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/qt.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/resources.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/moc.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/uic.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/unix/thread.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/yacc.prf:
../../Programs/Qt/5.4/gcc_64/mkspecs/features/lex.prf:
QmlGame.pro:
qml.qrc:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Quick.prl:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Gui.prl:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Core.prl:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Qml.prl:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Network.prl:
/home/ingmar/Programs/Qt/5.4/gcc_64/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QmlGame.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		MainMenu.qml \
		MenuItem.qml \
		Credits.qml \
		Game.qml \
		main.qml \
		images/line-border-clipart-line-border-designs-showcard_border.png
	/home/ingmar/Programs/Qt/5.4/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../Programs/Qt/5.4/gcc_64/include/QtWidgets/QApplication \
		../../Programs/Qt/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qglobal.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qconfig.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qlogging.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qflags.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qmutex.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qstring.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qchar.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qobject.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qlist.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qiterator.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qisenum.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qpoint.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qsize.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qcursor.h \
		../../Programs/Qt/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Programs/Qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qmargins.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qrect.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpalette.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qcolor.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qrgb.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qpair.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qregexp.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qbrush.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qvector.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qregion.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qline.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qtransform.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qimage.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qhash.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qfont.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../Programs/Qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qevent.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qvariant.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qmap.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qdebug.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qlocale.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qset.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qurl.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qfile.h \
		../../Programs/Qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../Programs/Qt/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qqmlengine.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qjsengine.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qjsvalue.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qqmlerror.h \
		../../Programs/Qt/5.4/gcc_64/include/QtQml/qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QmlGame/bin || mkdir -p $(INSTALL_ROOT)/opt/QmlGame/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/QmlGame/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/QmlGame/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QmlGame/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

